-- Refine the seeded taxonomy to Lone Peak's actual product (crawled
-- lonepeakoverland.com 8/12): signals now reference real accessories,
-- prebuild tiers and fitment trucks. Adds per-archetype ad_ids (specific
-- ad IDs to watch as a strong signal) and a prebuild-tier attribute.

alter table deal_archetypes add column if not exists ad_ids text[] not null default '{}';
comment on column deal_archetypes.ad_ids is 'Meta/Google ad IDs that strongly indicate this archetype; matched against a deal''s ad journey.';

update deal_archetypes set signals = array['Transcript keywords: elk, deer, antelope, tag, unit, draw, backcountry, glassing, pack out, rifle, bow','Asks about the Diesel Heater Port + 105Ah sub-zero heated LiFePO4 (cold mornings)','Wants Gear Vault, MOLLE panels, Squatch Spotter light bar for pre-dawn/night','Heavy fitment: F250/F350, Tundra, Ram 2500','Fall / pre-season timing; values the blackout tent for dark-thirty starts']::text[], updated_at = now() where key = 'hunter';
update deal_archetypes set signals = array['Transcript keywords: trail, ride, race, enduro, singletrack, watts, shuttle','Wants Load Bars + Heavy Duty Tie Downs for bikes','Drawn to the 15-second setup and ~400 lb light weight','Midsize fitment: Tacoma, Ranger, Colorado, Frontier','Weekend / race-weekend engagement timing']::text[], updated_at = now() where key = 'mtb_athlete';
update deal_archetypes set signals = array['Transcript keywords: kids, family, wife, husband, park, road trip, memories, summer','Wants Awning, Gear Vault w/ tables, Propane Tank Mount, Roof Vent Fan, 3-Zone Lighting, side/rear windows','Half-ton+ fitment: F150, Tundra, Silverado/Sierra 1500, Ram 1500','Gravitates to the Weekender / Adventurer prebuild']::text[], updated_at = now() where key = 'overland_family';
update deal_archetypes set signals = array['Transcript keywords: retired, retirement, full-time, bucket list, grandkids, travel','Comfort focus: Diesel Heater, 10gal Powered Water Tank, 3-Zone Lighting; asks about reliability + warranty','Often paying cash (0% APR financing less relevant)','Schedules a demo; longer, unhurried engagement history']::text[], updated_at = now() where key = 'retiree_adventurer';
update deal_archetypes set signals = array['Transcript keywords: weekend, quick trip, after work, easy, value','Loves the 15-second setup + lift-away platform; leans Baseline / Weekender prebuild','Dual-use daily driver; midsize or half-ton (Tacoma, F150, 1500)','Evening / weekend engagement timing']::text[], updated_at = now() where key = 'weekend_warrior';
update deal_archetypes set signals = array['Transcript keywords: remote work, wifi, Starlink, solar, power, office, full-time','Wants Power Plate (1000W inverter / Victron), 520W Solar, 105Ah LiFePO4, Juicebox, Solar Panel Wiring Port','Longer stays; Roof Vent Fan + windows for livability','Design- and interior-conscious']::text[], updated_at = now() where key = 'vanlife_remote';
update deal_archetypes set signals = array['Transcript keywords: off-grid, self-sufficient, redundancy, prepared, independent, water, power','Stacks Power Plate + 520W Solar + 105Ah battery + 10gal Water Tank + Propane + MOLLE','Gravitates to the Overlander prebuild (full power/solar)','Capability over comfort in questions']::text[], updated_at = now() where key = 'self_reliant';
update deal_archetypes set signals = array['Transcript keywords: fish, fishing, boat, kayak, paddleboard, lake, river, trout, bass','Wants Heavy Duty Tie Downs (kayaks/paddleboards/surfboards), Load Bars, Gear Vault','Remote water access; early-morning / late-evening use']::text[], updated_at = now() where key = 'angler';
update deal_archetypes set signals = array['Transcript keywords: photo, photography, landscape, golden hour, content, creator, brand','Gear protection: Gear Vault + Gear Bags; blackout tent for daytime rest','Aesthetics/design-forward; side/rear windows','Remote scenic destinations']::text[], updated_at = now() where key = 'photographer';
update deal_archetypes set signals = array['Transcript keywords: best, premium, top of the line, fully loaded, custom, nicest','Wants a fully-loaded Overlander prebuild + most accessories','Values made-to-order customization + modern look (integrated brake light, finish)','Low price sensitivity']::text[], updated_at = now() where key = 'status_lifestyle';
update deal_archetypes set signals = array['Transcript keywords: work, job, haul, durable, value, ROI, maintenance, rugged','Wants Cab Passthrough Window (lumber pass-through), Tall Edition clearance, Load Bars','Values V2 freeze/leak-proof latches + low maintenance','Work-truck fitment: F250/F350, Ram 2500, Silverado 2500']::text[], updated_at = now() where key = 'utilitarian';
update deal_archetypes set signals = array['Transcript keywords: ski, snowboard, snow, winter, resort, cold, heater, insulation','Wants Diesel Heater Port + 105Ah sub-zero heated battery; freeze-proof V2 latches','Resort-lot / backcountry overnighting','Winter engagement timing']::text[], updated_at = now() where key = 'snow_chaser';
update deal_archetypes set positive_traits = positive_traits || array['Values the cab passthrough window for hauling lumber / long loads']::text[], updated_at = now() where key = 'utilitarian';
update deal_archetypes set positive_traits = positive_traits || array['Cares about freeze-proof latches and sub-zero battery heating']::text[], updated_at = now() where key = 'snow_chaser';
update deal_archetypes set positive_traits = positive_traits || array['Wants full power/solar redundancy (Power Plate + 520W + LiFePO4)']::text[], updated_at = now() where key = 'self_reliant';
update profile_attributes set options = array['Cash','Financing interested (0% APR)','Unknown']::text[], updated_at = now() where key = 'financing';
update profile_attributes set description = 'Truck payload class — gates fitment. LPO fits Tacoma/Ranger/Colorado/Frontier (midsize) up to F350/Ram 2500/Silverado 2500 (heavy).', updated_at = now() where key = 'vehicle_class';
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('prebuild_tier','Prebuild interest','Which prebuilt config they gravitate to — maps to power/solar level.','Vehicle & Setup','single_select',array['Baseline','Weekender','Adventurer','Overlander','Full custom']::text[],55) on conflict (key) do nothing;