-- AI deal-profiling foundation (Phase 0): the editable taxonomy the engine
-- classifies against. deal_archetypes = blended personas (positive traits,
-- anti-traits for segregation, observable signals, selling guidance).
-- profile_attributes = the universal, archetype-independent dimensions every
-- profile tries to fill. Both admin-editable at /settings/archetypes. No AI
-- or per-deal profile yet — this is the vocabulary those will use.

create table if not exists deal_archetypes (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  name text not null,
  emoji text,
  tagline text,
  description text,
  positive_traits text[] not null default '{}',
  negative_traits text[] not null default '{}',
  signals text[] not null default '{}',
  selling_approach text,
  avoid text,
  sort_order int not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table deal_archetypes enable row level security;

create table if not exists profile_attributes (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  name text not null,
  description text,
  category text not null default 'General',
  value_type text not null default 'single_select'
    check (value_type in ('single_select','multi_select','scale','boolean','text')),
  options text[] not null default '{}',
  sort_order int not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table profile_attributes enable row level security;

insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('hunter','The Hunter','🏹','Backcountry pursuit, self-reliant, gear- and game-hauling.','Chases game into remote country and needs a rig that gets there, keeps them warm and dry, and hauls gear in and game out. Values capability and durability over comfort or looks.',array['Talks seasons, tags, units, draws','Wants remote / off-grid backcountry access','Prioritizes payload for gear and game','Values cold-weather warmth and dryness','Truck-first, capability over comfort','Mentions specific game (elk, deer, antelope)','Rifle / bow / optics storage matters','Early riser, long days in the field']::text[],array['Luxury- or aesthetics-first','Urban / on-pavement use only','''Glamping'' or comfort-led framing','No mention of remote or outdoors','Style over function']::text[],array['Keywords: elk, deer, hunt, tag, unit, draw, backcountry, rifle, bow, glassing, pack out','Interacted with hunting-season ads','Viewed heavy-payload / bare-bones builds','Fall / pre-season timing']::text[],'Lead with toughness, payload, cold-weather capability and remote self-sufficiency. Respect their expertise, be concise, skip the fluff.','Lifestyle and aesthetic pitches, ''glamping'' language, comfort-first framing.',10) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('mtb_athlete','The Mountain Biker / Endurance Athlete','🚵','Trailhead strike missions, gear transport, lightweight and fit.','Chases trails, races and rides. Wants quick-deploy basecamp at the trailhead, smart gear storage, and a rig that doesn''t weigh them down.',array['Mentions trails, rides, races, events','Needs bike / gear transport and storage','Values quick setup and teardown','Weekend-warrior cadence around events','Fitness- and performance-oriented','Cares about weight and drivability']::text[],array['Sedentary / static-living framing','Heavy full-time rig','No sport or activity mention']::text[],array['Keywords: trail, ride, race, enduro, singletrack, rack, watts','Interacted with lightweight / agile build ads','Viewed compact or fast-deploy builds']::text[],'Emphasize quick deploy, gear organization, low weight and chasing the season. Energetic, peer-to-peer tone.','Heavy, slow, static living pitches.',20) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('overland_family','The Overlanding Family / Fun Dad','👨‍👩‍👧‍👦','Memories, kids, comfort, ease and togetherness.','Wants to get the family outside and off screens. Prioritizes sleeping capacity, ease of use, safety and comfort — the rig is a memory-making machine.',array['Mentions kids, spouse, family trips','Needs sleeping capacity for 3+','Values ease of use and quick comfort','Safety-conscious','National / state parks, road trips','''Get the kids off screens'' motivation']::text[],array['Solo hardcore / minimalist','Extreme-remote or high-risk framing','Single with no family mention']::text[],array['Keywords: kids, family, wife, husband, park, road trip, summer, memories','Interacted with family-build ads','Viewed larger floorplans / more sleeping']::text[],'Sell togetherness, ease, safety, comfort and lasting memories. Warm, reassuring, patient.','Hardcore-remote, danger, or minimalist framing.',30) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('retiree_adventurer','The Retiree Adventurer / Full-Timer','🏕️','Freedom, time, comfort and reliability — finally.','Retired or near it, with time and budget to travel slow and comfortably. Prioritizes reliability, comfort and support over raw capability.',array['Retired or nearing retirement','Extended / slow travel plans','Comfort and reliability first','Budget available, less price-pressured','Bucket-list / ''finally have time'' framing','May mention grandkids, home-base flexibility']::text[],array['Tight budget, weekend-only','Extreme-sport framing','Urgent / immediate timeline']::text[],array['Keywords: retired, retirement, full-time, travel, bucket list, grandkids','Longer engagement history','Viewed comfort- and reliability-oriented builds']::text[],'Emphasize reliability, comfort, freedom, support and warranty. No rush — relationship-driven, patient.','High-pressure timelines, extreme-sport or bare-bones framing.',40) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('weekend_warrior','The Weekend Warrior','⛺','Busy career, weekend escapes, easy and dual-use.','Full-time job, escapes on weekends. Wants fast, easy, good value and a rig that pulls double duty as a daily driver.',array['Full-time career, limited time','Weekend / short-trip cadence','Wants easy, fast on/off','Value-conscious','Dual-use daily driver']::text[],array['Full-timer with unlimited time','No time or budget constraints','Pure hardcore-remote use']::text[],array['Keywords: weekend, quick trip, after work, easy, value','Evening / weekend engagement','Viewed easy-remove / dual-use builds']::text[],'Sell quick escapes, easy on/off, value and weekday practicality. Efficient, respect their time.','Full-time-living or unlimited-budget framing.',50) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('vanlife_remote','The Remote Worker / Van-Lifer','💻','Lives and works on the road — power, connectivity, workspace.','Works remotely and stays out longer. Needs power, connectivity and a comfortable workspace, and cares about design and livability.',array['Works remotely / on the road','Needs power, solar, connectivity','Wants usable workspace','Longer stays in one place','Design- and livability-conscious','Mentions wifi, Starlink, office']::text[],array['Weekend-only, no work-from-road','Pure utility with no livability need']::text[],array['Keywords: remote work, wifi, starlink, solar, power, office, full-time','Interacted with power / electrical build ads','Viewed livability- / interior-focused builds']::text[],'Lead with power systems, connectivity, comfortable workspace and design. Detail-oriented.','Bare-bones utility framing with no livability.',60) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('self_reliant','The Self-Reliant / Off-Gridder','🧭','Independence, capability, redundancy and off-grid readiness.','Values independence and being ready for anything. Prioritizes off-grid capability, redundancy (water, power) and durable, self-sufficient systems.',array['Self-sufficiency and independence','Off-grid capability, no hookups','Redundancy in water and power','Security and preparedness framing','Durability over comfort']::text[],array['Luxury- or status-driven','Depends on hookups / campgrounds','Aesthetics over capability']::text[],array['Keywords: off-grid, self-sufficient, water, solar, redundancy, prepared, independent','Viewed capability / systems-heavy builds']::text[],'Emphasize capability, redundancy, independence and durability. Straight-shooting, spec-forward.','Luxury, status or campground-dependent framing.',70) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('angler','The Fisherman / Angler','🎣','Remote water, gear hauling, odd-hour comfort.','Chases remote lakes and rivers. Needs to haul gear (and maybe a boat/kayak), reach the water, and be comfortable at dawn and dusk.',array['Mentions fishing spots, species, seasons','Hauls boat / kayak / gear','Wants remote water access','Early-morning / late-evening use']::text[],array['No water or fishing mention','Urban-only use']::text[],array['Keywords: fish, fishing, boat, kayak, lake, river, trout, bass','Viewed gear-hauling / tow-capable builds']::text[],'Sell gear hauling, remote water access and comfort at odd hours.','Pure on-pavement / urban framing.',80) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('photographer','The Photographer / Creator','📷','Chasing light and scenery, gear protection, aesthetics.','Chases scenery and light, sometimes for a living. Wants access to remote scenic spots, protected gear storage, and a rig that looks the part.',array['Mentions photography, landscapes, golden hour','Remote scenic destinations','Gear storage / protection matters','Aesthetics-conscious','May reference content / brand work']::text[],array['No creative / scenic mention','Pure utility with no aesthetics']::text[],array['Keywords: photo, photography, landscape, golden hour, content, creator','Viewed design- / aesthetics-forward builds']::text[],'Emphasize access to remote scenery, gear protection and clean design.','Bare-utility framing with no aesthetics.',90) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('status_lifestyle','The Status / Lifestyle Buyer','✨','Premium, design, brand and the best of the best.','Wants the top-tier product — driven more by design, craftsmanship, exclusivity and image than by spec sheets or price.',array['Wants premium / top-tier','Design and aesthetics first','Brand prestige and exclusivity','Social sharing / image','Less spec-driven, more image-driven']::text[],array['Budget- or value-first','Utility-only, indifferent to looks','Spec-obsessed']::text[],array['Keywords: best, premium, top of the line, design, custom, luxury','Viewed flagship / premium builds']::text[],'Sell premium materials, craftsmanship, exclusivity and design. Aspirational tone.','Value / budget positioning.',100) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('utilitarian','The Practical Utilitarian / Work Buyer','🔧','Job, utility, durability and ROI — no nonsense.','Buys for work or pure utility. Prioritizes durability, function, value and low maintenance. Contractor, rancher, guide, or just no-frills.',array['Work / utility use','Durability and low maintenance','ROI and value focus','No-frills, function-first','Contractor / rancher / guide']::text[],array['Aesthetics- or status-driven','Lifestyle / image framing','Comfort-first']::text[],array['Keywords: work, job, durable, value, ROI, maintenance, rugged','Viewed no-frills / utility builds']::text[],'Sell durability, function, value and low maintenance. Direct, numbers-driven.','Lifestyle, image or aesthetics pitches.',110) on conflict (key) do nothing;
insert into deal_archetypes (key,name,emoji,tagline,description,positive_traits,negative_traits,signals,selling_approach,avoid,sort_order) values ('snow_chaser','The Skier / Snow-Chaser','🎿','Winter capability, warmth, gear and resort/backcountry nights.','Chases snow, resort or backcountry. Needs cold-weather capability, warmth/heating, and gear storage for overnighting in the cold.',array['Mentions skiing / snowboarding','Cold-weather capability priority','Warmth and heating matter','Gear storage for winter kit','Resort-lot or backcountry overnighting']::text[],array['Warm-weather-only use','No cold-weather or snow mention']::text[],array['Keywords: ski, snowboard, snow, winter, resort, cold, heater, insulation','Interacted with winter / cold-weather ads','Viewed insulated / heated builds']::text[],'Emphasize insulation, heating, cold-weather capability and gear storage.','Warm-weather-only framing.',120) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('familial_status','Familial status','Household make-up — steers tone and floorplan needs.','Demographics & Life','single_select',array['Single','Couple','Young family (kids <10)','Established family (kids 10+)','Empty nester','Retiree','Multi-generational']::text[],10) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('region','Region','Where they''re based — terrain, seasons, travel patterns.','Demographics & Life','single_select',array['Mountain West','Pacific Northwest','Desert Southwest','Midwest','Southeast','Northeast','California','Texas','Canada','Other']::text[],20) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('home_base','Home base type','Living environment.','Demographics & Life','single_select',array['Urban','Suburban','Rural']::text[],30) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('vehicle_class','Vehicle payload class','Truck capability — gates which builds fit.','Vehicle & Setup','single_select',array['Midsize','Half-ton','3/4-ton','1-ton','Flatbed','Other / unknown']::text[],40) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('setup_stage','Setup stage','Where they are in their rig journey.','Vehicle & Setup','single_select',array['First-timer','Upgrading','Adding to fleet']::text[],50) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('activities','Primary activities','What they actually do outside — the strongest archetype driver.','Lifestyle & Use','multi_select',array['Hunting','Fishing','Mountain biking','Overlanding','Off-roading','Climbing','Skiing / snowboarding','Photography','Remote work','General camping','Water sports','Motorsports']::text[],60) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('use_intensity','Use intensity','How often the rig gets used.','Lifestyle & Use','scale',array['Occasional','Weekend','Frequent','Full-time']::text[],70) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('trip_style','Trip style','Typical trip length and shape.','Lifestyle & Use','single_select',array['Quick strikes','Long weekends','Week-long','Extended / full-time','Seasonal']::text[],80) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('travel_range','Travel range','How far they roam.','Lifestyle & Use','single_select',array['Local','Regional','Cross-country','International']::text[],90) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('budget_signal','Budget signal','Inferred spending comfort.','Buying Behavior','scale',array['Value','Mid','Premium','No constraint']::text[],100) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('buying_timeline','Buying timeline','How soon they intend to buy.','Buying Behavior','single_select',array['Immediate (<30d)','This season (<90d)','This year','Exploring / someday']::text[],110) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('decision_style','Decision style','What drives their decision — steers the pitch.','Buying Behavior','single_select',array['Spec / analytical','Lifestyle / emotional','Social proof','Price-driven']::text[],120) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('price_sensitivity','Price sensitivity','How much price steers them.','Buying Behavior','scale',array['High','Moderate','Low']::text[],130) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('financing','Financing interest','Payment posture.','Buying Behavior','single_select',array['Cash','Financing interested','Unknown']::text[],140) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('decision_role','Decision role','Who signs off.','Buying Behavior','single_select',array['Sole decision-maker','Joint (spouse/partner)','Needs buy-in']::text[],150) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('pref_channel','Preferred channel','Where they respond best.','Communication','single_select',array['Call','Text','Email','WhatsApp']::text[],160) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('comm_style','Communication style','How to talk to them.','Communication','single_select',array['Concise / direct','Detailed / thorough','Relationship / warm']::text[],170) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('responsiveness','Responsiveness','How quickly they engage.','Communication','scale',array['Fast','Moderate','Slow']::text[],180) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('best_contact_time','Best contact time','When they engage (from activity data).','Communication','single_select',array['Morning','Midday','Evening','Weekend']::text[],190) on conflict (key) do nothing;
insert into profile_attributes (key,name,description,category,value_type,options,sort_order) values ('build_motivation','Build motivation','The deeper ''why'' — the emotional driver behind the purchase.','Motivation','multi_select',array['Adventure / exploration','Family memories','Self-reliance / preparedness','Work / utility','Status / aesthetics','Freedom / escape','Fitness / sport']::text[],200) on conflict (key) do nothing;